### ISSUE TITLE
Add details to README

### ISSUE THREAD

**Issue by PLLE** [debajyotid2/ds-challenge#1]
Hey @debajyotid2, 
thank you for sharing your repository from the start! Really good practice! It would be really nice if you could add some description and getting started section to your readme so that it becomes easy for me to test and reproduce your results!

Thank you very much!

**Comment by debajyotid2** [comment]
Hello @PLLE ,

Thank you for bringing this up! I have updated the README with instructions on running the training and inference pipeline. If you face any further issues in running the scripts, please let me know!

Thanks.
